apiVersion: v1
kind: Namespace
metadata:
  name: app1-dev
  labels:
    app: app1
    env: dev
    
---
apiVersion: v1
kind: Pod
metadata:
  namespace: app1-dev
  labels:
    app: app1
    env: dev
spec:
  containers:
  - image: nginx:latest
    name: app1-dev 
    ports:            
    - containerPort: 80        # The Port the container is listening on
      protocol: TCP   
