apiVersion: v1
kind: Service
metadata:
  name: simple-lb
spec:
  selector:
    app: web
  ports:
    - protocol: TCP
      port: 80  # load balancer port  
      targetPort: 80  # conatainer port
  type: LoadBalancer