apiVersion: v1
kind: Namespace
metadata:
  name: application
---
apiVersion: v1
kind: Pod
metadata:
  name: httpd-pod
  namespace: application
spec:
  containers:
  - name: httpd-container
    image: paketobuildpacks/httpd:0.7
    ports:
    - containerPort: 80