apiVersion: apps/v1
kind: Deployment
metadata:
  name: super-app
  namespace: resources
spec:
  replicas: 2
  selector:
    matchLabels:
      app: super-app
  template:
    metadata:
      labels:
        app: super-app
    spec:
      containers:
      - name: nginx
        image: nginx
        resources:
          requests:
            cpu: "400m"
            memory: "1Gi"
